### PR TITLE
Capitalize keywords according to RFC 8174

### LINKED ISSUE #41: Doc has lots of lowercase "must" and "should"
A scrub for these to determine which are really requirements is a good idea.

Also, update SS1.1 to use RFC 8174 boilerplate.

### PR DESCRIPTION
**Pull request by liucougar**
closes #41

### CODE REVIEW

**Comment by tfpauly** [comment]
Does this also need to update the boilerplate text that defines SHOULD, MUST, etc?

**Comment by liucougar** [comment]
forgot to mention that, but the draft is already updated to use 8174 boilerplate

**Comment by klarose** [comment]
This LGTM. My only comment is that we still have a lot of lower-case requirements words, but I think that given their context they're okay to stay that way. I'd prefer if we could reword to avoid them, but it's probably fine to leave it this way.

**Comment by klarose** [comment]
In the paragraph starting at line 633, we say:

```
                  However, it may be possible to spoof the IP address, particularly for
                  malicious reasons where proper functioning of the network is not necessary
                  for the malicious actor. Consequently, any solution using the IP address
                  should proactively try to prevent spoofing of the IP address. Similarly,
                  if the mapping of IP address to User Equipment is changed, the components
                  of the architecture must remove or update their mapping to prevent spoofing.
                  Demonstrations of return routeability, such as that required for TCP
                  connection establishment, might be sufficient defense against spoofing,
                  though this might not be sufficient in networks that use broadcast media
                  (such as some wireless networks).
```

In particular, " Consequently, any solution using the IP address should proactively" and "the components  of the architecture must remove or update their"

I think we should either capitalize these two or rephrase them.

**Comment by klarose** [comment]
Aside from my one comment, lgtm. I don't think the intention of the issue was to rephrase everything that used lowercase, but to make sure that we captilized everything we needed to.

**Comment by liucougar** [comment]
changed the 2 to capital case

**Comment by klarose** [comment]
lgtm, thanks.

**Pull request merged**
